/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

/**
 *
 * @author Daiane
 */
public class teste extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcb_xveg = new javax.swing.JCheckBox();
        jcb_xsalada = new javax.swing.JCheckBox();
        jcb_xbacon = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jcb_suco = new javax.swing.JCheckBox();
        jcb_xmexico = new javax.swing.JCheckBox();
        jcb_refrilit = new javax.swing.JCheckBox();
        jcb_cerveja = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jrb_retirada = new javax.swing.JRadioButton();
        jrb_entrega = new javax.swing.JRadioButton();
        jtf_subtotal = new javax.swing.JTextField();
        jtf_total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_resetar = new javax.swing.JButton();
        label_background = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Chiller", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("La Barba");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 140, 60));

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lanches");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O melhor lanche da cidade!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jcb_xveg.setBackground(new java.awt.Color(17, 16, 14));
        jcb_xveg.setForeground(new java.awt.Color(255, 255, 255));
        jcb_xveg.setText("X-Veg R$10,00");
        jcb_xveg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_xvegActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_xveg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jcb_xsalada.setBackground(new java.awt.Color(17, 16, 14));
        jcb_xsalada.setForeground(new java.awt.Color(255, 255, 255));
        jcb_xsalada.setText("X-Salada R$12,00");
        jcb_xsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_xsaladaActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_xsalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jcb_xbacon.setBackground(new java.awt.Color(17, 16, 14));
        jcb_xbacon.setForeground(new java.awt.Color(255, 255, 255));
        jcb_xbacon.setText("X-Bacon R$15,00");
        jcb_xbacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_xbaconActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_xbacon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bebidas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, 40));

        jcb_suco.setBackground(new java.awt.Color(17, 16, 14));
        jcb_suco.setForeground(new java.awt.Color(250, 250, 250));
        jcb_suco.setText("Suco natural R$7,00");
        getContentPane().add(jcb_suco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jcb_xmexico.setBackground(new java.awt.Color(17, 16, 14));
        jcb_xmexico.setForeground(new java.awt.Color(255, 255, 255));
        jcb_xmexico.setText("X-México R$17,00");
        jcb_xmexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_xmexicoActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_xmexico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jcb_refrilit.setBackground(new java.awt.Color(17, 16, 14));
        jcb_refrilit.setForeground(new java.awt.Color(250, 250, 250));
        jcb_refrilit.setText("Refrigerante 2l R$8,50");
        getContentPane().add(jcb_refrilit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jcb_cerveja.setBackground(new java.awt.Color(17, 16, 14));
        jcb_cerveja.setForeground(new java.awt.Color(250, 250, 250));
        jcb_cerveja.setText("Cerveja em lata  R$3,50");
        jcb_cerveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_cervejaActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_cerveja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel6.setBackground(new java.awt.Color(17, 16, 14));
        jLabel6.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subtotal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 20));

        jrb_retirada.setBackground(new java.awt.Color(17, 16, 14));
        jrb_retirada.setForeground(new java.awt.Color(250, 250, 250));
        jrb_retirada.setText("Retirada R$0,00");
        jrb_retirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_retiradaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_retirada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jrb_entrega.setBackground(new java.awt.Color(17, 16, 14));
        jrb_entrega.setForeground(new java.awt.Color(250, 250, 250));
        jrb_entrega.setText("Entrega R$10,00");
        jrb_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_entregaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jtf_subtotal.setBackground(new java.awt.Color(17, 16, 14));
        jtf_subtotal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtf_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 70, -1));

        jtf_total.setBackground(new java.awt.Color(17, 16, 14));
        jtf_total.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jtf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 70, -1));

        jLabel8.setBackground(new java.awt.Color(17, 16, 14));
        jLabel8.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 50, 20));

        btn_calcular.setBackground(new java.awt.Color(255, 255, 255));
        btn_calcular.setText("Calcular");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setBackground(new java.awt.Color(17, 16, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/lanche.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        btn_resetar.setBackground(new java.awt.Color(255, 255, 255));
        btn_resetar.setText("Resetar");
        btn_resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resetar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        label_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/cardapio.png"))); // NOI18N
        getContentPane().add(label_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_xmexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_xmexicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_xmexicoActionPerformed

    private void jcb_xbaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_xbaconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_xbaconActionPerformed

    private void jcb_xvegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_xvegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_xvegActionPerformed

    private void jcb_xsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_xsaladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_xsaladaActionPerformed

    private void jcb_cervejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_cervejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_cervejaActionPerformed

    private void jrb_retiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_retiradaActionPerformed
        if(jrb_retirada.isSelected()){
            jrb_entrega.setSelected(false);
        }
    }//GEN-LAST:event_jrb_retiradaActionPerformed

    private void jrb_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_entregaActionPerformed
        if(jrb_entrega.isSelected()){
            jrb_retirada.setSelected(false);
        }
    }//GEN-LAST:event_jrb_entregaActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        double total=0;
        double subtotal=0;
        
        //CALCULANDO OS LANCHES
        if(jcb_xsalada.isSelected()){
            subtotal = subtotal + 12;
        } 
        if(jcb_xveg.isSelected()){
            subtotal = subtotal + 10;
        } 
        if(jcb_xbacon.isSelected()){
            subtotal = subtotal + 15;
        } 
        if(jcb_xmexico.isSelected()){
            subtotal = subtotal + 17;
        }
        //CALCULANDO AS BEBIDAS
        if(jcb_suco.isSelected()){
            subtotal = subtotal + 7;
        }
        if(jcb_refrilit.isSelected()){
            subtotal = subtotal +  8.50;
        } 
        if(jcb_cerveja.isSelected()){
            subtotal = subtotal + 3.50;
        } else{
            total = subtotal;
        }
        
        if(jrb_entrega.isSelected()){
            total = subtotal + 10;
        }else {
            total = subtotal;
        }
        jtf_total.setText(Double.toString(total));
        jtf_subtotal.setText(Double.toString(subtotal));
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetarActionPerformed
        jtf_total.setText("");
        jtf_subtotal.setText("");
        jcb_cerveja.setSelected(false);
        jcb_xsalada.setSelected(false);
        jcb_xveg.setSelected(false);
        jcb_xbacon.setSelected(false);
        jcb_xmexico.setSelected(false);
        jcb_suco.setSelected(false);
        jcb_refrilit.setSelected(false);
        if(jrb_entrega.isSelected()){
            jrb_entrega.setSelected(false);
        }
        if(jrb_retirada.isSelected()){
            jrb_retirada.setSelected(false);
        }
    }//GEN-LAST:event_btn_resetarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_resetar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JCheckBox jcb_cerveja;
    private javax.swing.JCheckBox jcb_refrilit;
    private javax.swing.JCheckBox jcb_suco;
    private javax.swing.JCheckBox jcb_xbacon;
    private javax.swing.JCheckBox jcb_xmexico;
    private javax.swing.JCheckBox jcb_xsalada;
    private javax.swing.JCheckBox jcb_xveg;
    private javax.swing.JRadioButton jrb_entrega;
    private javax.swing.JRadioButton jrb_retirada;
    private javax.swing.JTextField jtf_subtotal;
    private javax.swing.JTextField jtf_total;
    private javax.swing.JLabel label_background;
    // End of variables declaration//GEN-END:variables
}
